# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phone_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
