# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_signup_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone_no',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
