# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170114_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
