# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170114_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
